# Example observability configuration for RAG engine

# Basic observability settings
observability_enabled: true
observability_provider: "langfuse"  # Options: "langfuse", "phoenix", "disabled"
observability_sample_rate: 1.0  # 0.0 to 1.0, controls what percentage of traces to capture

# Langfuse configuration
langfuse_secret_key: "sk-lf-..."  # Your Langfuse secret key
langfuse_public_key: "pk-lf-..."  # Your Langfuse public key
langfuse_host: "https://cloud.langfuse.com"  # Optional, defaults to cloud.langfuse.com

# Phoenix configuration (for future use)
phoenix_endpoint: "http://localhost:6006"  # Phoenix server endpoint
phoenix_api_key: null  # Phoenix API key if required

# Tracing feature flags
trace_llm_calls: true      # Trace LLM generation calls
trace_retrieval: true      # Trace document retrieval operations
trace_embeddings: true     # Trace embedding generation
trace_evaluation: true     # Trace evaluation runs

# Data capture settings
capture_inputs: true       # Capture input data in traces
capture_outputs: true      # Capture output data in traces
capture_metadata: true     # Capture additional metadata

# Performance settings
flush_interval: 10         # Seconds between automatic flushes
max_batch_size: 100        # Maximum batch size for trace uploads